### ISSUE TITLE
what is it?

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/comrade#7]
https://github.com/97Dima97/comrade/blob/012eef01d57bf7a2d41ff9b1df3317f5280d3311/app.test.js#L2

пишешь, что пакеты установил, а почему здесь используется старый синтаксис. Не наблюдают конфига на бабель в корне. Посмотри как сделано у тебя для learning-programs и также сделай

**Comment by 97Dima97** [comment]
все установил.
