### ISSUE TITLE
order in your code

### ISSUE THREAD

**Issue by pure-amber** [97Dima97/comrade#8]
https://github.com/97Dima97/comrade/blob/012eef01d57bf7a2d41ff9b1df3317f5280d3311/index.js#L1

попробуем упорядочить код: вынеси всю функциональность в отдельный файл в директорию src. Директорию создай в корне. Из index.js просто вызывай эту функцию с функциональностью

**Comment by 97Dima97** [comment]
упорядочил .
по новой папке src
